export const appIcons = {
  home: require('../asset/icons/home.png'),
  randomQuestion: require('../asset/icons/random.png'),
  exam: require('../asset/icons/test.png'),
  wrongAnswer: require('../asset/icons/wrong.png'),
  review: require('../asset/icons/book.png'),
  arrowRight: require('../asset/icons/right-arrow.png'),
  arrowLeft: require('../asset/icons/left-arrow.png'),
  popup: require('../asset/icons/pop-up.png'),
  share: require('../asset/icons/share.png'),
  sum: require('../asset/icons/sum.png'),
  tick: require('../asset/icons/tick.png'),
  warning: require('../asset/icons/exclamation-point.png'),
  clock: require('../asset/icons/clock.png'),
  refresh: require('../asset/icons/refresh.png'),
};

export const questionImages = {
  71: require('../asset/questions/71.jpg'),
  72: require('../asset/questions/72.jpg'),
  73: require('../asset/questions/73.jpg'),
  74: require('../asset/questions/74.jpg'),
  75: require('../asset/questions/75.jpg'),
  76: require('../asset/questions/76.jpg'),
  77: require('../asset/questions/77.jpg'),
  78: require('../asset/questions/78.jpg'),
  79: require('../asset/questions/79.jpg'),
  80: require('../asset/questions/80.jpg'),
  81: require('../asset/questions/81.jpg'),
  82: require('../asset/questions/82.jpg'),
  83: require('../asset/questions/83.jpg'),
  84: require('../asset/questions/84.jpg'),
  85: require('../asset/questions/85.jpg'),
  86: require('../asset/questions/86.jpg'),
  87: require('../asset/questions/87.jpg'),
  88: require('../asset/questions/88.jpg'),
  89: require('../asset/questions/89.jpg'),
  90: require('../asset/questions/90.jpg'),
  91: require('../asset/questions/91.jpg'),
  92: require('../asset/questions/92.jpg'),
  93: require('../asset/questions/93.jpg'),
  94: require('../asset/questions/94.jpg'),
  95: require('../asset/questions/95.jpg'),
  96: require('../asset/questions/96.jpg'),
  97: require('../asset/questions/97.jpg'),
  98: require('../asset/questions/98.jpg'),
  99: require('../asset/questions/99.jpg'),
  100: require('../asset/questions/100.jpg'),
};
