// Danh sách câu trả lời của thí sinh
const SET_LIST_8_GROUP_EXAM = 'SET_LIST_8_GROUP_EXAM';
const SET_IS_FINISH_EXAM = 'SET_IS_FINISH_EXAM';
const SET_REFRESH_FINISH_EXAM = 'SET_REFRESH_FINISH_EXAM';
const SET_CORRECT_ANSWER_LIST = 'SET_CORRECT_ANSWER_LIST';
// const SET = 'SET_CURRENT_WRONG_QUESTION';
// const SET_IS_SHOW_ANSWER = 'SET_IS_SHOW_ANSWER';
// const SET_CURRENT_CHOSEN_ANSWER = 'SET_CURRENT_CHOSEN_ANSWER';

export {
  SET_LIST_8_GROUP_EXAM,
  SET_IS_FINISH_EXAM,
  SET_REFRESH_FINISH_EXAM,
  SET_CORRECT_ANSWER_LIST,
};
