// Danh sách câu trả lời của thí sinh
const SET_LIST_CHOSEN_EXAM_QUESTION = 'SET_LIST_CHOSEN_EXAM_QUESTION';
const SET_CURRENT_EXAM_QUESTION = 'SET_CURRENT_WRONG_QUESTION';
const SET_IS_SHOW_ANSWER = 'SET_IS_SHOW_ANSWER';
// const SET_CURRENT_CHOSEN_ANSWER = 'SET_CURRENT_CHOSEN_ANSWER';

export {
  SET_LIST_CHOSEN_EXAM_QUESTION,
  SET_CURRENT_EXAM_QUESTION,
  SET_IS_SHOW_ANSWER,
  // SET_CURRENT_CHOSEN_ANSWER,
};
